//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class студенческая_библиотекаEntities1 : DbContext
    {
        public студенческая_библиотекаEntities1()
            : base("name=студенческая_библиотекаEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Авторы> Авторы { get; set; }
        public virtual DbSet<Библиотекари> Библиотекари { get; set; }
        public virtual DbSet<Возвраты> Возвраты { get; set; }
        public virtual DbSet<Выдачи> Выдачи { get; set; }
        public virtual DbSet<Жанры> Жанры { get; set; }
        public virtual DbSet<Книги> Книги { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
    }
}
