//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Возвраты
    {
        public int ID_Возврата { get; set; }
        public int ID_Выдачи { get; set; }
        public System.DateTime Дата_Возврата { get; set; }
        public string Состояние { get; set; }
    
        public virtual Выдачи Выдачи { get; set; }
    }
}
