//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Выдачи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Выдачи()
        {
            this.Возвраты = new HashSet<Возвраты>();
        }
    
        public int ID_Выдачи { get; set; }
        public int ID_Книги { get; set; }
        public int ID_Студента { get; set; }
        public int ID_Библиотекаря { get; set; }
        public System.DateTime Дата_Выдачи { get; set; }
        public System.DateTime Срок_Возврата { get; set; }
    
        public virtual Библиотекари Библиотекари { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Возвраты> Возвраты { get; set; }
        public virtual Книги Книги { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
