//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Книги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Книги()
        {
            this.Выдачи = new HashSet<Выдачи>();
        }
    
        public int ID_Книги { get; set; }
        public string Название { get; set; }
        public int ID_Автора { get; set; }
        public int ID_Жанра { get; set; }
        public Nullable<int> Год_Издания { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Авторы Авторы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Выдачи> Выдачи { get; set; }
        public virtual Жанры Жанры { get; set; }
    }
}
